### ISSUE TITLE
Cant get VCI4 running

### ISSUE THREAD

**Issue by NICO-SOLUTIONS** [gmarescotti/ixxatcan#3]
Dear gmarescotti,
i tried to setup the IXXAT VCI plugin for qt.
I programmed a VCI3 application for C++ Builder a while ago, but as i want to switch to QT, it seems liek i need to start almost from scratch. 
I found this codehere on git, but as mentioned i can not get it running in Qt 5.15.0. qtixxatcanbusd.pdb is not created for some reasons.

Just a quick question... Did you manage to get this running as a thread within an application wihtout using the "CAN Example"-sample? If not i think i will go for a complete new approach by transfering my C++ Builder VCI3 code to VCI4 in Qt.

All the best

**Comment by gmarescotti** [comment]
Hello,

 I suggest you to goggle for [qt not generate pdb], I see that there is some hints for that.
 If you need I could make some investigation with Qt 5.15 in the next days.
Which compiler are you using?

p.s. I have successfully used the plugin in an application in a thread.

Best regards,
Giulio

**Comment by NICO-SOLUTIONS** [comment]
Dear gmarescotti,
many thanks for your reply. I will do some further digging concerning the pdb-files. If you would find the time to try to get it running in 5.15, would be great. But as you already used it in the past, i think it should be managable to adapt it to my needs somehow.

I´ll let you know if there is something new
All the best
Nils

Edit: forgot to mention the compiler:
Tried it with MSVC2019 (32/64bit) & and did some initial tests using MinGW (32/64bit)...
