### ISSUE TITLE
Plugin recognized but doesn't work

### ISSUE THREAD

**Issue by hoxuanduong** [gmarescotti/ixxatcan#4]
Hi Gmarescotti,
thanks very much for your works.
i'm following your instruction and test with CAN bus example from Qt.
Here is Qt Info:
Qt Creator 4.14.0
Based on Qt 5.15.2 (MSVC 2019, 64 bit)
I use window 10.
i ran CAN bus example from Qt. The IXXAT plugin is recognized.

here is the log in Qt Creator Application Output when i try sending:
"****[QIPCAP] Cert free handle 
Function Name:  class QList<class QCanBusDeviceInfo> __cdecl IxxatCanBackend::interfaces(void)
HW484553 HMS Technology Center Ravensburg GmbH USB-to-CAN V2 compact
Function Name:  __cdecl IxxatCanBackend::IxxatCanBackend(const class QString &)
Function Name:  bool __cdecl IxxatCanBackend::open(void)
Function Name:  bool __cdecl IxxatCanBackend::writeFrame(const class QCanBusFrame &)
Function Name:  bool __cdecl IxxatCanBackend::writeFrame(const class QCanBusFrame &)
"
I added debug message to function void IxxatCanBackend::recv (CanMessage * frame) and have following log in Application Output when receiving:
"
****[QIPCAP] Cert free handle 
Function Name:  class QList<class QCanBusDeviceInfo> __cdecl IxxatCanBackend::interfaces(void)
HW484553 HMS Technology Center Ravensburg GmbH USB-to-CAN V2 compact
Function Name:  __cdecl IxxatCanBackend::IxxatCanBackend(const class QString &)
Function Name:  bool __cdecl IxxatCanBackend::open(void)
Function Name:  void __cdecl IxxatCanBackend::recv(class QCanBusFrame *)
Function Name:  void __cdecl IxxatCanBackend::recv(class QCanBusFrame *)
Function Name:  void __cdecl IxxatCanBackend::recv(class QCanBusFrame *)
"

I actually can neither send nor receive. Do you have any idea what should be problem?
BR

**Comment by gmarescotti** [comment]
Hi,
thanks for contacting me, and sorry for the late reply..

I see from your logs that maybe its the adapter that is different from what the driver is configured for.

I tested the driver with:
[link to ixxat adapter](https://www.ixxat.com/products/products-industrial/can-interfaces/usb-can-interfaces/usb-to-can-v2-professional?ordercode=1.01.0281.12001)

What is your usb adapter?

I hope that you solved your issue in the meanwhile....

Regards,
Giulio

**Comment by hoxuanduong** [comment]
Hi Giulio,
thanks for your reply. i use exactly the same Ixxat adapter.
USB-to-CAN V2 compact (odernummer: 1.01.0281.12001)

actually the receive works but send doesn't work.

when i debug at following code, ret is always false
"
bool MainWindow::sendFrame(const QCanBusFrame &frame) const
{
    if (!m_canDevice)
        return false;
    bool ret;
    m_canDevice->writeFrame(frame);
    ret = m_canDevice->waitForFramesWritten(100);
    return ret;
}
"

the framewritten signal is triggered and sent message is increased.

void MainWindow::processFramesWritten(qint64 count)
{
    m_numberFramesWritten += count;
    m_written->setText(tr("%1 frames written").arg(m_numberFramesWritten));
}

i couldn't follow exactly your instruction in readme. because the installed folder in my computer is different.
i have compiled your can plugin project and copy following files to C:\Qt\5.12.2\msvc2017_64\plugins\canbus
qtixxatcanbus.dll
qtixxatcanbus.pdb
qtixxatcanbusd.dll
qtixxatcanbusd.pdb
and following files to C:\Qt\5.12.2\msvc2017_64\lib
qtixxatcanbusd.lib
qtixxatcanbus.lib

in the ixxatcan project source code, function bool IxxatCanBackend::writeFrame(const QCanBusFrame &newData)
lots of codes are commented out and nowhere write function is called, only emit framesWritten(1);
Regards
Ho

**Comment by gmarescotti** [comment]
Hi,
sorry but I can't manage to identify the problem without further info.
Could you please share your code (or part of your code),
so I can test on my machine?

Thank you,
Giulio

**Comment by FelixBetz** [comment]
> Hi Gmarescotti,
> thanks very much for your works.
> i'm following your instruction and test with CAN bus example from Qt.
> Here is Qt Info:
> Qt Creator 4.14.0
> Based on Qt 5.15.2 (MSVC 2019, 64 bit)
> I use window 10.
> i ran CAN bus example from Qt. The IXXAT plugin is recognized.
> ......

Hi, 
I think I have the same problem @hoxuanduong described in his comment.
What I did: 
1. Clone this repo into folder "C:\Qt\5.15.2\Src\qtserialbus\src\plugins\canbus"
2. edit "C:\Qt\5.15.2\Src\qtserialbus\src\plugins\canbus\canbus.pro" file
`qtConfig(library) {
    SUBDIRS += passthrucan peakcan tinycan ixxatcan
    win32 {
        SUBDIRS += systeccan
        !winrt:SUBDIRS += vectorcan
    }
}
`
2. open "C:\Qt\5.15.2\Src\qtserialbus\src\plugins\canbus\ixxatcan\ixxatcan.pro" file
3. compile with Desktop_Qt_5_15_2_MSVC**2019**_64bit-Release and Qt Creator 4.13.3 (!difference to  your installation manual, you used MSCV2017 => maybe this could be a problem)
4. copy qtixxatcanbus.dll and qtixxatcanbusd.pdb into "C:\Qt\5.15.2\msvc2019_64\plugins\canbus" folder
5. open example project: "C:\Qt\Examples\Qt-5.15.2\serialbus\can\can.pro"
6. Compile with "build-can-Desktop_Qt_5_15_2_MSVC2019_64bit-Release"
7. Plugin Ixxact USB-to-CAN V2 and run the program
8. my device shows up:
![image](https://user-images.githubusercontent.com/23038103/108372932-9f692780-71ff-11eb-9e0a-b66f015760b4.png)
9.  Click Connect with a coustom configuration
![image](https://user-images.githubusercontent.com/23038103/108373776-8c0a8c00-7200-11eb-95e3-c87d7e7d13de.png)

10. I get following application output:
`Function Name:  class QList<class QCanBusDeviceInfo> __cdecl IxxatCanBackend::interfaces(void)`
`HW588393 HMS Technology Center Ravensburg GmbH USB-to-CAN V2 compact`
`Function Name:  __cdecl IxxatCanBackend::IxxatCanBackend(const class QString &)`
`Function Name:  bool __cdecl IxxatCanBackend::open(void)`
12. the GUI shows following message:
![image](https://user-images.githubusercontent.com/23038103/108373474-38983e00-7200-11eb-96ed-53abb76902e3.png)
13. When I try to send a message I get following  application ouput, but no CAN Message is send
`Function Name:  bool __cdecl IxxatCanBackend::writeFrame(const class QCanBusFrame &)`
14. Receiving messages works fine:
![image](https://user-images.githubusercontent.com/23038103/108373914-b1979580-7200-11eb-8f10-6bb3a288b160.png)

I did not change a single line of code in your project and in the SerialBus example project. 
Only difference I can figure out is, that I am using the MSVC2019 compiler. 
Can you confirm this? Or do you have an idea why your code isn't working with MSCV2019?

Would be nice if you can help me.
Best Regards
Felix

**Comment by hoxuanduong** [comment]
Hi
i have fixed it.

file ixxatcanbackend.cpp

in function

bool IxxatCanBackend::writeFrame(const QCanBusFrame &newData)

add the following line of code

if(!driver->send((CanMessage*)(&newData))) return false;

and messages are actually sent out

hope it helps
BR
Ho

**Comment by FelixBetz** [comment]
Wow! 
Thanks for your fast Response.
It works. 
Best Regards
Do you make a pull request?
Felix
